const fs = require('fs');
const path = require('path');
const { createScaffold } = require('./scaffold-generator');

function writeFileIfContent(filePath, content) {
  if (content === null || content === undefined) return false;
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, 'utf8');
  return true;
}

function wrapPrototypeHtml(prototypeHtml) {
  if (!prototypeHtml || !prototypeHtml.trim()) return '';
  return `<!DOCTYPE html>\n<html>\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n</head>\n<body>\n${prototypeHtml}\n</body>\n</html>`;
}

function prototypeFromBlueprint(blueprint = '') {
  const htmlBlockMatch = String(blueprint || '').match(/```html\s*([\s\S]*?)\s*```/i);
  if (!htmlBlockMatch?.[1]) return '';

  const prototypeHtml = htmlBlockMatch[1].trim();
  const hasAlpine = /alpinejs|x-data|x-show|x-for|@click|x-on:/i.test(prototypeHtml);
  const hasAlpineCdn = /cdn\.jsdelivr\.net\/npm\/alpinejs|unpkg\.com\/alpinejs/i.test(prototypeHtml);
  const alpineScript = hasAlpine && !hasAlpineCdn
    ? '\n        <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>'
    : '';

  return `<!DOCTYPE html>\n<html>\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <style>\n    * { box-sizing: border-box; }\n    body { margin: 0; min-height: 100vh; }\n  </style>${alpineScript}\n</head>\n<body>\n${prototypeHtml}\n</body>\n</html>`;
}

function copyWorkspaceFiles({ workspace, sessionId, projectPath }) {
  const buildFilesList = [];
  if (!workspace || !sessionId) return buildFilesList;

  const wsDir = workspace.workspaceDir(sessionId);
  if (!fs.existsSync(wsDir)) return buildFilesList;

  const copyRecursive = (src, dest) => {
    fs.mkdirSync(dest, { recursive: true });
    const entries = fs.readdirSync(src, { withFileTypes: true });
    for (const entry of entries) {
      const srcPath = path.join(src, entry.name);
      const destPath = path.join(dest, entry.name);
      if (entry.isDirectory()) {
        copyRecursive(srcPath, destPath);
      } else {
        fs.copyFileSync(srcPath, destPath);
        buildFilesList.push(path.relative(projectPath, destPath));
      }
    }
  };

  copyRecursive(wsDir, projectPath);
  return buildFilesList;
}

function buildReadme({ projectName, agentId, templateId, projectType }) {
  const scaffoldLabel = templateId || 'html-alpine';
  return `# ${projectName}\n\nGenerated by Cauldron OS as a build-agent handoff package.\n\n## Included\n\n- \`blueprint.md\` — product and implementation specification\n- \`prototype.html\` — standalone HTML prototype when available\n- \`design-system.md\` — selected design reference content\n- \`cauldron.project.json\` — machine-readable handoff manifest\n- \`agent-prompt.md\` — prompt for your build agent CLI\n- \`.opencode/config.md\` — OpenCode-oriented manual instructions\n- Scaffold starter files for \`${scaffoldLabel}\`\n\n## Run The Scaffold\n\n- Static/HTML templates: open \`index.html\` in a browser.\n- Package templates: run \`npm install\`, then \`npm run dev\`.\n\n## Build With Your Agent\n\n1. Open this folder in your preferred coding agent.\n2. Read \`agent-prompt.md\` first.\n3. Use \`blueprint.md\`, \`prototype.html\`, and \`design-system.md\` as the source of truth.\n4. Build a runnable ${scaffoldLabel || projectType || 'project'} scaffold.\n5. Keep implementation notes and any remaining setup steps in this README.\n\nRequested agent: ${agentId || 'handoff-only'}\n`;
}

function buildAgentPrompt({ projectName, templateId, projectType }) {
  return `You are building ${projectName} from a Cauldron OS handoff package.\n\nRead these files first:\n\n1. blueprint.md\n2. prototype.html, if present\n3. design-system.md\n4. cauldron.project.json\n\nBuild the most useful runnable ${templateId || projectType || 'project'} version from the spec. Preserve the visual direction from the prototype and design system. Add realistic local demo data where needed. Do not require real secrets; create .env.example for credentials. Finish by updating README.md with run instructions and remaining caveats.`;
}

function buildCursorRules() {
  return `# Cursor Rules for Cauldron Handoff\n\n- Read agent-prompt.md, blueprint.md, prototype.html, and design-system.md before editing.\n- Build a runnable project from the handoff package; do not replace the spec with a new plan.\n- Preserve the selected design system and prototype interaction model.\n- Add accessible states, responsive layout, and realistic demo data.\n- Document setup and run commands in README.md.\n`;
}

function buildOpenCodeConfig({ projectName }) {
  return `# ${projectName}\n\nGenerated by Cauldron OS.\n\n## What's included\n\n- \`blueprint.md\` — full product specification\n- \`prototype.html\` — live HTML/AlpineJS prototype when available\n- \`design-system.md\` — selected design reference\n- \`agent-prompt.md\` — prompt to run with OpenCode or another CLI agent\n- \`cauldron.project.json\` — machine-readable handoff manifest\n\n## Build this project\n\n1. Open this folder in your terminal\n2. Run: \`opencode\`\n3. Paste or reference \`agent-prompt.md\`\n4. Use your preferred model\n\n---\nCauldron saves the handoff package; you own the model and final build decision.\n`;
}

function createHandoffPackage({
  projectPath,
  projectName,
  safeName,
  cauldronVersion,
  blueprint = '',
  prototypeHtml = '',
  designReference = 'none',
  designSystemContent = '',
  templateId = '',
  projectType = 'app',
  sessionId = '',
  workspace = null,
  agentId = 'handoff',
  command = null,
}) {
  fs.mkdirSync(projectPath, { recursive: true });

  const buildFilesList = copyWorkspaceFiles({ workspace, sessionId, projectPath });
  let useBlueprint = blueprint;

  if (sessionId && !useBlueprint) {
    try {
      const files = workspace.wsListFiles(sessionId);
      useBlueprint = `# Build Session: ${safeName}\n\nCopied ${buildFilesList.length} files from build session ${sessionId}.\n\n## Files\n${files.map(f => `- ${f}`).join('\n')}`;
    } catch {
      useBlueprint = `# Build Session: ${safeName}\n\nBuild handoff from session ${sessionId}.`;
    }
  }

  const files = {};
  if (writeFileIfContent(path.join(projectPath, 'blueprint.md'), useBlueprint || '')) files.blueprint = 'blueprint.md';

  const fullPrototype = wrapPrototypeHtml(prototypeHtml) || prototypeFromBlueprint(useBlueprint);
  if (fullPrototype) {
    writeFileIfContent(path.join(projectPath, 'prototype.html'), fullPrototype);
    files.prototype = 'prototype.html';
  }

  const designSystemMarkdown = designSystemContent && designSystemContent.trim()
    ? designSystemContent
    : `# Design Reference\n\nSelected design reference: ${designReference || 'none'}\n`;
  writeFileIfContent(path.join(projectPath, 'design-system.md'), designSystemMarkdown);
  files.designSystem = 'design-system.md';

  writeFileIfContent(path.join(projectPath, 'README.md'), buildReadme({ projectName, agentId, templateId, projectType }));
  files.readme = 'README.md';

  writeFileIfContent(path.join(projectPath, 'agent-prompt.md'), buildAgentPrompt({ projectName, templateId, projectType }));
  files.agentPrompt = 'agent-prompt.md';

  writeFileIfContent(path.join(projectPath, '.cursorrules'), buildCursorRules());
  files.cursorRules = '.cursorrules';

  writeFileIfContent(path.join(projectPath, '.opencode', 'config.md'), buildOpenCodeConfig({ projectName }));
  files.opencodeConfig = '.opencode/config.md';

  const scaffold = createScaffold({
    projectPath,
    projectName,
    safeName,
    templateId,
    projectType,
    blueprint: useBlueprint,
    prototypeHtml: fullPrototype,
  });
  files.scaffold = scaffold.paths;
  files.manifest = 'cauldron.project.json';

  const manifest = {
    schemaVersion: 1,
    projectName: safeName,
    displayName: projectName,
    createdAt: new Date().toISOString(),
    source: 'cauldron-os',
    cauldronVersion,
    projectType,
    templateId,
    designReference: designReference || 'none',
    sessionId: sessionId || null,
    files,
    copiedWorkspaceFiles: buildFilesList,
    scaffold,
    agent: {
      mode: command ? 'launched' : 'handoff-only',
      requestedCli: agentId === 'handoff' ? null : agentId,
      command,
    },
  };

  writeFileIfContent(path.join(projectPath, 'cauldron.project.json'), JSON.stringify(manifest, null, 2) + '\n');

  return {
    projectPath,
    manifestPath: path.join(projectPath, 'cauldron.project.json'),
    files,
    filesCopied: buildFilesList.length,
    blueprint: useBlueprint || '',
    manifest,
  };
}

module.exports = {
  createHandoffPackage,
  prototypeFromBlueprint,
  wrapPrototypeHtml,
};
