const fs = require('fs');
const path = require('path');
const { createScaffold, bootstrapScaffold } = require('./scaffold-generator');
const { buildDesignPackage } = require('./design-system-export');
const { parseSessionId } = require('./path-safety');

function writeFileIfContent(filePath, content) {
  if (content === null || content === undefined) return false;
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, 'utf8');
  return true;
}

function wrapPrototypeHtml(prototypeHtml) {
  if (!prototypeHtml || !prototypeHtml.trim()) return '';
  return `<!DOCTYPE html>\n<html>\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n</head>\n<body>\n${prototypeHtml}\n</body>\n</html>`;
}

function prototypeFromBlueprint(blueprint = '') {
  const htmlBlockMatch = String(blueprint || '').match(/```html\s*([\s\S]*?)\s*```/i);
  if (!htmlBlockMatch?.[1]) return '';

  const prototypeHtml = htmlBlockMatch[1].trim();
  const hasAlpine = /alpinejs|x-data|x-show|x-for|@click|x-on:/i.test(prototypeHtml);
  const hasAlpineCdn = /cdn\.jsdelivr\.net\/npm\/alpinejs|unpkg\.com\/alpinejs/i.test(
    prototypeHtml
  );
  const alpineScript =
    hasAlpine && !hasAlpineCdn
      ? '\n        <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>'
      : '';

  return `<!DOCTYPE html>\n<html>\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <style>\n    * { box-sizing: border-box; }\n    body { margin: 0; min-height: 100vh; }\n  </style>${alpineScript}\n</head>\n<body>\n${prototypeHtml}\n</body>\n</html>`;
}

function copyWorkspaceFiles({ workspace, sessionId, projectPath }) {
  const buildFilesList = [];
  const safeSessionId = parseSessionId(sessionId);
  if (!workspace || !safeSessionId) return buildFilesList;

  const wsDir = workspace.workspaceDir(safeSessionId);
  if (!fs.existsSync(wsDir)) return buildFilesList;

  const copyRecursive = (src, dest) => {
    fs.mkdirSync(dest, { recursive: true });
    const entries = fs.readdirSync(src, { withFileTypes: true });
    for (const entry of entries) {
      const srcPath = path.join(src, entry.name);
      const destPath = path.join(dest, entry.name);
      if (entry.isDirectory()) {
        copyRecursive(srcPath, destPath);
      } else {
        fs.copyFileSync(srcPath, destPath);
        buildFilesList.push(path.relative(projectPath, destPath));
      }
    }
  };

  copyRecursive(wsDir, projectPath);
  return buildFilesList;
}

const AGENT_SCOPES = {
  handoff: {
    label: 'General implementation handoff',
    focus:
      'Own the complete build handoff. Turn the blueprint, prototype, and design system into the most useful runnable project.',
    files: ['blueprint.md', 'prototype.html', 'design-system.md', 'README.md'],
  },
  cursor: {
    label: 'Frontend UI implementation',
    focus:
      'Own the visual implementation: layout, components, responsive CSS, interactions, accessibility states, and front-end polish.',
    files: ['prototype.html', 'design-system.md', 'index.html', 'styles.css', 'app.js'],
  },
  codex: {
    label: 'Architecture, API, and tests',
    focus:
      'Own project structure, API/data contracts, smoke tests, edge cases, and verification. Keep implementation aligned to the blueprint.',
    files: ['blueprint.md', 'cauldron.project.json', 'package.json', 'tests/'],
  },
  claude: {
    label: 'Review, test, and documentation',
    focus:
      'Own critique, test planning, edge-case review, documentation, and implementation notes. Tighten the handoff into something maintainable.',
    files: ['blueprint.md', 'README.md', 'agent-prompt.md'],
  },
  hermes: {
    label: 'Implementation continuity',
    focus:
      'Own cross-file implementation continuity, task sequencing, and finishing work that connects frontend, scaffold, and docs.',
    files: ['blueprint.md', 'prototype.html', 'cauldron.project.json'],
  },
  opencode: {
    label: 'Local CLI build execution',
    focus:
      'Own terminal-native build execution, local project setup, file edits, and runnable scaffold completion.',
    files: ['agent-prompt.md', '.opencode/config.md', 'blueprint.md'],
  },
};

function getAgentScope(agentId = 'handoff') {
  return AGENT_SCOPES[agentId] || AGENT_SCOPES.handoff;
}

function buildReadme({ projectName, agentId, templateId, projectType, agentScope = null }) {
  const scaffoldLabel = templateId || 'html-alpine';
  const scope = agentScope || getAgentScope(agentId);
  return `# ${projectName}\n\nGenerated by Cauldron OS as a build-agent handoff package.\n\n## Included\n\n- \`blueprint.md\` — product and implementation specification\n- \`prototype.html\` — standalone HTML prototype when available\n- \`design-system.md\` — selected design reference content\n- \`launch-checklist.md\` — human runbook and verification summary\n- \`cauldron.project.json\` — machine-readable handoff manifest\n- \`agent-prompt.md\` — prompt for your build agent CLI\n- \`.opencode/config.md\` — OpenCode-oriented manual instructions\n- Scaffold starter files for \`${scaffoldLabel}\`\n\n## Run The Scaffold\n\n- Static/HTML templates: open \`index.html\` in a browser.\n- Package templates: run \`npm install\`, then \`npm run dev\`.\n\n## Build With Your Agent\n\n1. Open this folder in your preferred coding agent.\n2. Read \`agent-prompt.md\` first.\n3. Use \`blueprint.md\`, \`prototype.html\`, and \`design-system.md\` as the source of truth.\n4. Check \`launch-checklist.md\` for commands, verification results, and remaining human steps.\n5. Build a runnable ${scaffoldLabel || projectType || 'project'} scaffold.\n6. Keep implementation notes and any remaining setup steps in this README.\n\nRequested agent: ${agentId || 'handoff-only'}\n\n## Agent Scope\n\n${scope.label}\n\n${scope.focus}\n`;
}

function buildAgentPrompt({
  projectName,
  templateId,
  projectType,
  agentId = 'handoff',
  agentScope = null,
  orchestration = null,
}) {
  const scope = agentScope || getAgentScope(agentId);
  const siblingNotes =
    Array.isArray(orchestration?.agents) && orchestration.agents.length > 1
      ? `\n\n## Multi-Agent Context\nYou are one agent in a coordinated build handoff. Other selected agents: ${orchestration.agents.map((agent) => agent.name || agent.id).join(', ')}.\nStay inside your scope, but leave clear notes for the rest of the build team.`
      : '';

  return `You are building ${projectName} from a Cauldron OS handoff package.\n\n## Your Scope\n${scope.label}\n\n${scope.focus}\n\nPrimary files to inspect first:\n${scope.files.map((file) => `- ${file}`).join('\n')}\n\nRead these files before editing:\n\n1. blueprint.md\n2. prototype.html, if present\n3. design-system.md\n4. cauldron.project.json\n\nBuild the most useful runnable ${templateId || projectType || 'project'} version from the spec. Preserve the visual direction from the prototype and design system. Add realistic local demo data where needed. Do not require real secrets; create .env.example for credentials. Finish by updating README.md with run instructions and remaining caveats.${siblingNotes}`;
}

function buildCursorRules() {
  return `# Cursor Rules for Cauldron Handoff\n\n- Read agent-prompt.md, blueprint.md, prototype.html, and design-system.md before editing.\n- Build a runnable project from the handoff package; do not replace the spec with a new plan.\n- Preserve the selected design system and prototype interaction model.\n- Add accessible states, responsive layout, and realistic demo data.\n- Document setup and run commands in README.md.\n`;
}

function buildOpenCodeConfig({ projectName }) {
  return `# ${projectName}\n\nGenerated by Cauldron OS.\n\n## What's included\n\n- \`blueprint.md\` — full product specification\n- \`prototype.html\` — live HTML/AlpineJS prototype when available\n- \`design-system.md\` — selected design reference\n- \`launch-checklist.md\` — generated runbook and next steps\n- \`agent-prompt.md\` — prompt to run with OpenCode or another CLI agent\n- \`cauldron.project.json\` — machine-readable handoff manifest\n\n## Build this project\n\n1. Open this folder in your terminal\n2. Run: \`opencode\`\n3. Paste or reference \`agent-prompt.md\`\n4. Use your preferred model\n\n---\nCauldron saves the handoff package; you own the model and final build decision.\n`;
}

function readEnvExample(projectPath) {
  const envPath = path.join(projectPath, '.env.example');
  if (!fs.existsSync(envPath)) return [];
  return fs
    .readFileSync(envPath, 'utf8')
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith('#') && line.includes('='))
    .map((line) => line.split('=')[0].trim())
    .filter(Boolean);
}

function buildSmokeHint(scaffold = {}) {
  switch (scaffold.templateId || scaffold.id) {
    case 'nextjs':
      return 'You will know it worked when `npm run dev` starts cleanly and the homepage loads at `http://localhost:3000`.';
    case 'astro':
      return 'You will know it worked when `npm run dev` starts cleanly and the Astro homepage renders locally.';
    case 'static-html':
    case 'html-alpine':
      return 'You will know it worked when `index.html` opens without missing local assets and the primary user journey is visible.';
    default:
      return 'You will know it worked when the scaffold starts cleanly and the entrypoint renders without missing local assets.';
  }
}

function buildLaunchChecklist({
  projectName,
  scaffold,
  verification = null,
  designReference = 'none',
  createdAt,
  projectPath,
}) {
  const envVars = readEnvExample(projectPath);
  const commands = scaffold?.commands || {};
  const checks = Array.isArray(verification?.checks) ? verification.checks : [];
  const warnings = checks
    .filter((check) => check.status !== 'passed')
    .map(
      (check) => `- ${check.label}: ${check.status}${check.command ? ` (${check.command})` : ''}`
    );
  const skippedChecks = checks
    .filter((check) => check.status === 'skipped' || check.status === 'not_configured')
    .map((check) => `- ${check.label}: ${check.status}`);
  const commandList = Object.keys(commands).length
    ? Object.entries(commands)
        .map(([name, command]) => `- ${name}: \`${command}\``)
        .join('\n')
    : '- Open `index.html` directly in a browser.';
  const envList = envVars.length
    ? envVars.map((name) => `- \`${name}\``).join('\n')
    : '- No `.env.example` file was generated for this scaffold.';
  const warningList = warnings.length ? warnings.join('\n') : '- None.';
  const skippedList = skippedChecks.length ? skippedChecks.join('\n') : '- None.';

  return `# Launch checklist\n\n## Project\n\n- Name: ${projectName}\n- Generated: ${createdAt}\n- Template: ${scaffold?.templateId || scaffold?.id || 'unknown'}\n- Entrypoint: \`${scaffold?.entrypoint || 'unknown'}\`\n- Design reference: \`${designReference || 'none'}\`\n\n## Run commands\n\n${commandList}\n\n## Required environment variables\n\n${envList}\n\n## Verification summary\n\n- Overall: ${verification?.overall || 'Not run'}\n- Passed: ${verification?.summary?.passed || 0}\n- Failed: ${verification?.summary?.failed || 0}\n- Warnings: ${(verification?.summary?.skipped || 0) + (verification?.summary?.not_configured || 0)}\n\n### Skipped or not configured checks\n\n${skippedList}\n\n## Known limitations and warnings\n\n${warningList}\n\n## Human actions still required\n\n- Run the scaffold locally and confirm the core journey works in a browser.\n- Replace demo content, temporary copy, and local placeholders with production-ready implementation details.\n- Add real environment values outside this package if the final build needs external services.\n\n## Success check\n\n${buildSmokeHint(scaffold)}\n\n## Related files\n\n- [Blueprint](./blueprint.md)\n- [Prototype](./prototype.html)\n- [Design reference](./design-system.md)\n- [Manifest](./cauldron.project.json)\n- [Launch checklist](./launch-checklist.md)\n`;
}

async function createHandoffPackage({
  projectPath,
  projectName,
  safeName,
  cauldronVersion,
  blueprint = '',
  prototypeHtml = '',
  designReference = 'none',
  designSystemContent = '',
  templateId = '',
  projectType = 'app',
  sessionId = '',
  workspace = null,
  agentId = 'handoff',
  agentScope = null,
  orchestration = null,
  command = null,
  bootstrap = false,
  verification = null,
  includeDesignPackage = false,
}) {
  fs.mkdirSync(projectPath, { recursive: true });

  const buildFilesList = copyWorkspaceFiles({ workspace, sessionId, projectPath });
  let useBlueprint = blueprint;

  if (sessionId && !useBlueprint) {
    try {
      const files = workspace.wsListFiles(sessionId);
      useBlueprint = `# Build Session: ${safeName}\n\nCopied ${buildFilesList.length} files from build session ${sessionId}.\n\n## Files\n${files.map((f) => `- ${f}`).join('\n')}`;
    } catch {
      useBlueprint = `# Build Session: ${safeName}\n\nBuild handoff from session ${sessionId}.`;
    }
  }

  const files = {};
  if (writeFileIfContent(path.join(projectPath, 'blueprint.md'), useBlueprint || ''))
    files.blueprint = 'blueprint.md';

  const fullPrototype = wrapPrototypeHtml(prototypeHtml) || prototypeFromBlueprint(useBlueprint);
  if (fullPrototype) {
    writeFileIfContent(path.join(projectPath, 'prototype.html'), fullPrototype);
    files.prototype = 'prototype.html';
  }

  const designSystemMarkdown =
    designSystemContent && designSystemContent.trim()
      ? designSystemContent
      : `# Design Reference\n\nSelected design reference: ${designReference || 'none'}\n`;
  writeFileIfContent(path.join(projectPath, 'design-system.md'), designSystemMarkdown);
  files.designSystem = 'design-system.md';

  let designPackage = null;
  if (includeDesignPackage) {
    designPackage = buildDesignPackage({
      designReference,
      designSystemContent: designSystemMarkdown,
      prototypeHtml: fullPrototype,
    });
    writeFileIfContent(path.join(projectPath, 'docs', 'design.md'), designPackage.markdown);
    writeFileIfContent(path.join(projectPath, 'docs', 'design.html'), designPackage.html);
    files.designPackage = {
      markdown: 'docs/design.md',
      html: 'docs/design.html',
    };
  }

  const scope = agentScope || getAgentScope(agentId);

  writeFileIfContent(
    path.join(projectPath, 'README.md'),
    buildReadme({ projectName, agentId, templateId, projectType, agentScope: scope })
  );
  files.readme = 'README.md';

  writeFileIfContent(
    path.join(projectPath, 'agent-prompt.md'),
    buildAgentPrompt({
      projectName,
      templateId,
      projectType,
      agentId,
      agentScope: scope,
      orchestration,
    })
  );
  files.agentPrompt = 'agent-prompt.md';

  writeFileIfContent(path.join(projectPath, '.cursorrules'), buildCursorRules());
  files.cursorRules = '.cursorrules';

  writeFileIfContent(
    path.join(projectPath, '.opencode', 'config.md'),
    buildOpenCodeConfig({ projectName })
  );
  files.opencodeConfig = '.opencode/config.md';

  const scaffold = createScaffold({
    projectPath,
    projectName,
    safeName,
    templateId,
    projectType,
    blueprint: useBlueprint,
    prototypeHtml: fullPrototype,
  });
  files.scaffold = scaffold.paths;
  files.manifest = 'cauldron.project.json';

  let bootstrapResult = null;
  if (bootstrap && scaffold.packageManager) {
    bootstrapResult = await bootstrapScaffold(projectPath, scaffold.id);
  }

  writeFileIfContent(
    path.join(projectPath, 'launch-checklist.md'),
    buildLaunchChecklist({
      projectName,
      scaffold,
      verification,
      designReference,
      createdAt: new Date().toISOString(),
      projectPath,
    })
  );
  files.launchChecklist = 'launch-checklist.md';

  const manifest = {
    schemaVersion: 1,
    projectName: safeName,
    displayName: projectName,
    createdAt: new Date().toISOString(),
    source: 'cauldron-os',
    cauldronVersion,
    projectType,
    templateId,
    designReference: designReference || 'none',
    sessionId: sessionId || null,
    files,
    copiedWorkspaceFiles: buildFilesList,
    scaffold,
    bootstrap: bootstrapResult,
    verification,
    exports: {
      designPackage: includeDesignPackage
        ? {
            markdown: 'docs/design.md',
            html: 'docs/design.html',
          }
        : null,
    },
    agent: {
      mode: command ? 'launched' : 'handoff-only',
      requestedCli: agentId === 'handoff' ? null : agentId,
      command,
      scope,
    },
  };

  writeFileIfContent(
    path.join(projectPath, 'cauldron.project.json'),
    JSON.stringify(manifest, null, 2) + '\n'
  );

  return {
    projectPath,
    manifestPath: path.join(projectPath, 'cauldron.project.json'),
    files,
    filesCopied: buildFilesList.length,
    blueprint: useBlueprint || '',
    manifest,
    bootstrap: bootstrapResult,
  };
}

module.exports = {
  buildLaunchChecklist,
  createHandoffPackage,
  getAgentScope,
  prototypeFromBlueprint,
  wrapPrototypeHtml,
};
